// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'backends/distrobox/distrobox.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<String> getDistroboxVersion() =>
    RustLib.instance.api.crateApiGetDistroboxVersion();

Future<bool> isDistroboxInstalled() =>
    RustLib.instance.api.crateApiIsDistroboxInstalled();

Future<List<ContainerInfo>> getContainers() =>
    RustLib.instance.api.crateApiGetContainers();

Future<String> createContainer({required CreateArgs args}) =>
    RustLib.instance.api.crateApiCreateContainer(args: args);

Stream<String> streamTaskOutput({required String taskId}) =>
    RustLib.instance.api.crateApiStreamTaskOutput(taskId: taskId);

/// Remove/delete a container
Future<String> removeContainer({required String name}) =>
    RustLib.instance.api.crateApiRemoveContainer(name: name);

/// Stop a running container
Future<String> stopContainer({required String name}) =>
    RustLib.instance.api.crateApiStopContainer(name: name);

/// Stop all running containers
Future<String> stopAllContainers() =>
    RustLib.instance.api.crateApiStopAllContainers();

/// Upgrade packages in a container (returns task_id for streaming output)
Future<String> upgradeContainer({required String name}) =>
    RustLib.instance.api.crateApiUpgradeContainer(name: name);

/// Clone a container to create a new one
Future<String> cloneContainer(
        {required String sourceName, required CreateArgs args}) =>
    RustLib.instance.api
        .crateApiCloneContainer(sourceName: sourceName, args: args);

/// Get the command to enter a container (for terminal integration)
Future<List<String>> getEnterCommand({required String name}) =>
    RustLib.instance.api.crateApiGetEnterCommand(name: name);

/// List all applications in a container
Future<List<AppInfo>> listContainerApps({required String containerName}) =>
    RustLib.instance.api
        .crateApiListContainerApps(containerName: containerName);

/// Export an application from a container to the host
Future<String> exportApp(
        {required String containerName, required String desktopFilePath}) =>
    RustLib.instance.api.crateApiExportApp(
        containerName: containerName, desktopFilePath: desktopFilePath);

/// Unexport an application from the host
Future<String> unexportApp(
        {required String containerName, required String desktopFilePath}) =>
    RustLib.instance.api.crateApiUnexportApp(
        containerName: containerName, desktopFilePath: desktopFilePath);

/// List exported binaries from a container
Future<List<ExportedBinary>> listExportedBinaries(
        {required String containerName}) =>
    RustLib.instance.api
        .crateApiListExportedBinaries(containerName: containerName);

/// Export a binary from a container to the host
Future<String> exportBinary(
        {required String containerName, required String binaryPath}) =>
    RustLib.instance.api.crateApiExportBinary(
        containerName: containerName, binaryPath: binaryPath);

/// Unexport a binary from the host
Future<String> unexportBinary(
        {required String containerName, required String binaryPath}) =>
    RustLib.instance.api.crateApiUnexportBinary(
        containerName: containerName, binaryPath: binaryPath);

/// List available/compatible images for container creation
Future<List<String>> listAvailableImages() =>
    RustLib.instance.api.crateApiListAvailableImages();

/// Get a list of all active task IDs
Future<List<String>> getActiveTasks() =>
    RustLib.instance.api.crateApiGetActiveTasks();

/// Check if a task is still running
Future<bool> isTaskRunning({required String taskId}) =>
    RustLib.instance.api.crateApiIsTaskRunning(taskId: taskId);

/// Cancel/abort a running task (if possible)
Future<bool> cancelTask({required String taskId}) =>
    RustLib.instance.api.crateApiCancelTask(taskId: taskId);

/// Detect the package manager used in a container (apt, dnf, pacman, etc.)
Future<String> detectPackageManager({required String containerName}) =>
    RustLib.instance.api
        .crateApiDetectPackageManager(containerName: containerName);

/// List installed packages in a container
Future<List<PackageInfo>> listInstalledPackages(
        {required String containerName}) =>
    RustLib.instance.api
        .crateApiListInstalledPackages(containerName: containerName);

/// Search for packages in a container's repositories
Future<List<PackageInfo>> searchPackages(
        {required String containerName, required String query}) =>
    RustLib.instance.api
        .crateApiSearchPackages(containerName: containerName, query: query);

/// Install a package in a container (returns task_id for streaming output)
Future<String> installPackage(
        {required String containerName, required String packageName}) =>
    RustLib.instance.api.crateApiInstallPackage(
        containerName: containerName, packageName: packageName);

/// Remove a package from a container (returns task_id for streaming output)
Future<String> removePackage(
        {required String containerName, required String packageName}) =>
    RustLib.instance.api.crateApiRemovePackage(
        containerName: containerName, packageName: packageName);

/// Create a snapshot of a container
Future<String> createSnapshot(
        {required String containerName, required String snapshotName}) =>
    RustLib.instance.api.crateApiCreateSnapshot(
        containerName: containerName, snapshotName: snapshotName);

/// List available snapshots (optionally filtered by prefix)
Future<List<SnapshotInfo>> listSnapshots({String? filterPrefix}) =>
    RustLib.instance.api.crateApiListSnapshots(filterPrefix: filterPrefix);

/// Delete a snapshot
Future<String> deleteSnapshot({required String snapshotNameOrId}) =>
    RustLib.instance.api
        .crateApiDeleteSnapshot(snapshotNameOrId: snapshotNameOrId);

/// Restore a container from a snapshot (creates a new container)
Future<String> restoreFromSnapshot(
        {required String snapshotName, required String newContainerName}) =>
    RustLib.instance.api.crateApiRestoreFromSnapshot(
        snapshotName: snapshotName, newContainerName: newContainerName);

/// Export a container to a tar archive (returns task_id for streaming output)
Future<String> exportContainerToFile(
        {required String containerName, required String outputPath}) =>
    RustLib.instance.api.crateApiExportContainerToFile(
        containerName: containerName, outputPath: outputPath);

/// Import a container from a tar archive (returns task_id for streaming output)
Future<String> importContainerFromFile(
        {required String archivePath, required String imageName}) =>
    RustLib.instance.api.crateApiImportContainerFromFile(
        archivePath: archivePath, imageName: imageName);

/// Get resource usage statistics for a container
Future<ContainerStats> getContainerStats({required String containerName}) =>
    RustLib.instance.api
        .crateApiGetContainerStats(containerName: containerName);

/// Run an arbitrary command inside a container
Future<String> runCommandInContainer(
        {required String containerName, required String command}) =>
    RustLib.instance.api.crateApiRunCommandInContainer(
        containerName: containerName, command: command);

/// Represents an application that can be exported from a container
class AppInfo {
  final String name;
  final String exec;
  final String icon;
  final String desktopFilePath;
  final bool isExported;

  const AppInfo({
    required this.name,
    required this.exec,
    required this.icon,
    required this.desktopFilePath,
    required this.isExported,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      exec.hashCode ^
      icon.hashCode ^
      desktopFilePath.hashCode ^
      isExported.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          exec == other.exec &&
          icon == other.icon &&
          desktopFilePath == other.desktopFilePath &&
          isExported == other.isExported;
}

/// Represents a binary that has been exported from a container
class ExportedBinary {
  final String name;
  final String sourcePath;
  final String exportedPath;

  const ExportedBinary({
    required this.name,
    required this.sourcePath,
    required this.exportedPath,
  });

  @override
  int get hashCode =>
      name.hashCode ^ sourcePath.hashCode ^ exportedPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportedBinary &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          sourcePath == other.sourcePath &&
          exportedPath == other.exportedPath;
}
