// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'backends/distrobox/distrobox.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1080372141;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'gosh_distrobox_manager',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiCancelTask({required String taskId});

  Future<String> crateApiCloneContainer(
      {required String sourceName, required CreateArgs args});

  Future<String> crateApiCreateContainer({required CreateArgs args});

  Future<String> crateApiCreateSnapshot(
      {required String containerName, required String snapshotName});

  Future<String> crateApiDeleteSnapshot({required String snapshotNameOrId});

  Future<String> crateApiDetectPackageManager({required String containerName});

  Future<String> crateApiExportApp(
      {required String containerName, required String desktopFilePath});

  Future<String> crateApiExportBinary(
      {required String containerName, required String binaryPath});

  Future<String> crateApiExportContainerToFile(
      {required String containerName, required String outputPath});

  Future<List<String>> crateApiGetActiveTasks();

  Future<ContainerStats> crateApiGetContainerStats(
      {required String containerName});

  Future<List<ContainerInfo>> crateApiGetContainers();

  Future<String> crateApiGetDistroboxVersion();

  Future<List<String>> crateApiGetEnterCommand({required String name});

  Future<String> crateApiImportContainerFromFile(
      {required String archivePath, required String imageName});

  Future<void> crateApiInitApp();

  Future<String> crateApiInstallPackage(
      {required String containerName, required String packageName});

  Future<bool> crateApiIsDistroboxInstalled();

  Future<bool> crateApiIsTaskRunning({required String taskId});

  Future<List<String>> crateApiListAvailableImages();

  Future<List<AppInfo>> crateApiListContainerApps(
      {required String containerName});

  Future<List<ExportedBinary>> crateApiListExportedBinaries(
      {required String containerName});

  Future<List<PackageInfo>> crateApiListInstalledPackages(
      {required String containerName});

  Future<List<SnapshotInfo>> crateApiListSnapshots({String? filterPrefix});

  Future<String> crateApiRemoveContainer({required String name});

  Future<String> crateApiRemovePackage(
      {required String containerName, required String packageName});

  Future<String> crateApiRestoreFromSnapshot(
      {required String snapshotName, required String newContainerName});

  Future<String> crateApiRunCommandInContainer(
      {required String containerName, required String command});

  Future<List<PackageInfo>> crateApiSearchPackages(
      {required String containerName, required String query});

  Future<String> crateApiStopAllContainers();

  Future<String> crateApiStopContainer({required String name});

  Stream<String> crateApiStreamTaskOutput({required String taskId});

  Future<String> crateApiUnexportApp(
      {required String containerName, required String desktopFilePath});

  Future<String> crateApiUnexportBinary(
      {required String containerName, required String binaryPath});

  Future<String> crateApiUpgradeContainer({required String name});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiCancelTask({required String taskId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(taskId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCancelTaskConstMeta,
      argValues: [taskId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCancelTaskConstMeta => const TaskConstMeta(
        debugName: "cancel_task",
        argNames: ["taskId"],
      );

  @override
  Future<String> crateApiCloneContainer(
      {required String sourceName, required CreateArgs args}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sourceName, serializer);
        sse_encode_box_autoadd_create_args(args, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCloneContainerConstMeta,
      argValues: [sourceName, args],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCloneContainerConstMeta => const TaskConstMeta(
        debugName: "clone_container",
        argNames: ["sourceName", "args"],
      );

  @override
  Future<String> crateApiCreateContainer({required CreateArgs args}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_create_args(args, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCreateContainerConstMeta,
      argValues: [args],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateContainerConstMeta => const TaskConstMeta(
        debugName: "create_container",
        argNames: ["args"],
      );

  @override
  Future<String> crateApiCreateSnapshot(
      {required String containerName, required String snapshotName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        sse_encode_String(snapshotName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCreateSnapshotConstMeta,
      argValues: [containerName, snapshotName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateSnapshotConstMeta => const TaskConstMeta(
        debugName: "create_snapshot",
        argNames: ["containerName", "snapshotName"],
      );

  @override
  Future<String> crateApiDeleteSnapshot({required String snapshotNameOrId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(snapshotNameOrId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDeleteSnapshotConstMeta,
      argValues: [snapshotNameOrId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteSnapshotConstMeta => const TaskConstMeta(
        debugName: "delete_snapshot",
        argNames: ["snapshotNameOrId"],
      );

  @override
  Future<String> crateApiDetectPackageManager({required String containerName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDetectPackageManagerConstMeta,
      argValues: [containerName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDetectPackageManagerConstMeta =>
      const TaskConstMeta(
        debugName: "detect_package_manager",
        argNames: ["containerName"],
      );

  @override
  Future<String> crateApiExportApp(
      {required String containerName, required String desktopFilePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        sse_encode_String(desktopFilePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiExportAppConstMeta,
      argValues: [containerName, desktopFilePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportAppConstMeta => const TaskConstMeta(
        debugName: "export_app",
        argNames: ["containerName", "desktopFilePath"],
      );

  @override
  Future<String> crateApiExportBinary(
      {required String containerName, required String binaryPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        sse_encode_String(binaryPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiExportBinaryConstMeta,
      argValues: [containerName, binaryPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportBinaryConstMeta => const TaskConstMeta(
        debugName: "export_binary",
        argNames: ["containerName", "binaryPath"],
      );

  @override
  Future<String> crateApiExportContainerToFile(
      {required String containerName, required String outputPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        sse_encode_String(outputPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiExportContainerToFileConstMeta,
      argValues: [containerName, outputPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportContainerToFileConstMeta =>
      const TaskConstMeta(
        debugName: "export_container_to_file",
        argNames: ["containerName", "outputPath"],
      );

  @override
  Future<List<String>> crateApiGetActiveTasks() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetActiveTasksConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetActiveTasksConstMeta => const TaskConstMeta(
        debugName: "get_active_tasks",
        argNames: [],
      );

  @override
  Future<ContainerStats> crateApiGetContainerStats(
      {required String containerName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_container_stats,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGetContainerStatsConstMeta,
      argValues: [containerName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetContainerStatsConstMeta => const TaskConstMeta(
        debugName: "get_container_stats",
        argNames: ["containerName"],
      );

  @override
  Future<List<ContainerInfo>> crateApiGetContainers() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_container_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGetContainersConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetContainersConstMeta => const TaskConstMeta(
        debugName: "get_containers",
        argNames: [],
      );

  @override
  Future<String> crateApiGetDistroboxVersion() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGetDistroboxVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetDistroboxVersionConstMeta =>
      const TaskConstMeta(
        debugName: "get_distrobox_version",
        argNames: [],
      );

  @override
  Future<List<String>> crateApiGetEnterCommand({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetEnterCommandConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetEnterCommandConstMeta => const TaskConstMeta(
        debugName: "get_enter_command",
        argNames: ["name"],
      );

  @override
  Future<String> crateApiImportContainerFromFile(
      {required String archivePath, required String imageName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(archivePath, serializer);
        sse_encode_String(imageName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiImportContainerFromFileConstMeta,
      argValues: [archivePath, imageName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImportContainerFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "import_container_from_file",
        argNames: ["archivePath", "imageName"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<String> crateApiInstallPackage(
      {required String containerName, required String packageName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        sse_encode_String(packageName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInstallPackageConstMeta,
      argValues: [containerName, packageName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInstallPackageConstMeta => const TaskConstMeta(
        debugName: "install_package",
        argNames: ["containerName", "packageName"],
      );

  @override
  Future<bool> crateApiIsDistroboxInstalled() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiIsDistroboxInstalledConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIsDistroboxInstalledConstMeta =>
      const TaskConstMeta(
        debugName: "is_distrobox_installed",
        argNames: [],
      );

  @override
  Future<bool> crateApiIsTaskRunning({required String taskId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(taskId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiIsTaskRunningConstMeta,
      argValues: [taskId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIsTaskRunningConstMeta => const TaskConstMeta(
        debugName: "is_task_running",
        argNames: ["taskId"],
      );

  @override
  Future<List<String>> crateApiListAvailableImages() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiListAvailableImagesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiListAvailableImagesConstMeta =>
      const TaskConstMeta(
        debugName: "list_available_images",
        argNames: [],
      );

  @override
  Future<List<AppInfo>> crateApiListContainerApps(
      {required String containerName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_app_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiListContainerAppsConstMeta,
      argValues: [containerName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiListContainerAppsConstMeta => const TaskConstMeta(
        debugName: "list_container_apps",
        argNames: ["containerName"],
      );

  @override
  Future<List<ExportedBinary>> crateApiListExportedBinaries(
      {required String containerName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_exported_binary,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiListExportedBinariesConstMeta,
      argValues: [containerName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiListExportedBinariesConstMeta =>
      const TaskConstMeta(
        debugName: "list_exported_binaries",
        argNames: ["containerName"],
      );

  @override
  Future<List<PackageInfo>> crateApiListInstalledPackages(
      {required String containerName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_package_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiListInstalledPackagesConstMeta,
      argValues: [containerName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiListInstalledPackagesConstMeta =>
      const TaskConstMeta(
        debugName: "list_installed_packages",
        argNames: ["containerName"],
      );

  @override
  Future<List<SnapshotInfo>> crateApiListSnapshots({String? filterPrefix}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(filterPrefix, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_snapshot_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiListSnapshotsConstMeta,
      argValues: [filterPrefix],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiListSnapshotsConstMeta => const TaskConstMeta(
        debugName: "list_snapshots",
        argNames: ["filterPrefix"],
      );

  @override
  Future<String> crateApiRemoveContainer({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiRemoveContainerConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRemoveContainerConstMeta => const TaskConstMeta(
        debugName: "remove_container",
        argNames: ["name"],
      );

  @override
  Future<String> crateApiRemovePackage(
      {required String containerName, required String packageName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        sse_encode_String(packageName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiRemovePackageConstMeta,
      argValues: [containerName, packageName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRemovePackageConstMeta => const TaskConstMeta(
        debugName: "remove_package",
        argNames: ["containerName", "packageName"],
      );

  @override
  Future<String> crateApiRestoreFromSnapshot(
      {required String snapshotName, required String newContainerName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(snapshotName, serializer);
        sse_encode_String(newContainerName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiRestoreFromSnapshotConstMeta,
      argValues: [snapshotName, newContainerName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRestoreFromSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "restore_from_snapshot",
        argNames: ["snapshotName", "newContainerName"],
      );

  @override
  Future<String> crateApiRunCommandInContainer(
      {required String containerName, required String command}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        sse_encode_String(command, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiRunCommandInContainerConstMeta,
      argValues: [containerName, command],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRunCommandInContainerConstMeta =>
      const TaskConstMeta(
        debugName: "run_command_in_container",
        argNames: ["containerName", "command"],
      );

  @override
  Future<List<PackageInfo>> crateApiSearchPackages(
      {required String containerName, required String query}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        sse_encode_String(query, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_package_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSearchPackagesConstMeta,
      argValues: [containerName, query],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchPackagesConstMeta => const TaskConstMeta(
        debugName: "search_packages",
        argNames: ["containerName", "query"],
      );

  @override
  Future<String> crateApiStopAllContainers() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiStopAllContainersConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStopAllContainersConstMeta => const TaskConstMeta(
        debugName: "stop_all_containers",
        argNames: [],
      );

  @override
  Future<String> crateApiStopContainer({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiStopContainerConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStopContainerConstMeta => const TaskConstMeta(
        debugName: "stop_container",
        argNames: ["name"],
      );

  @override
  Stream<String> crateApiStreamTaskOutput({required String taskId}) {
    final sink = RustStreamSink<String>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(taskId, serializer);
        sse_encode_StreamSink_String_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 32, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiStreamTaskOutputConstMeta,
      argValues: [taskId, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiStreamTaskOutputConstMeta => const TaskConstMeta(
        debugName: "stream_task_output",
        argNames: ["taskId", "sink"],
      );

  @override
  Future<String> crateApiUnexportApp(
      {required String containerName, required String desktopFilePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        sse_encode_String(desktopFilePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiUnexportAppConstMeta,
      argValues: [containerName, desktopFilePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUnexportAppConstMeta => const TaskConstMeta(
        debugName: "unexport_app",
        argNames: ["containerName", "desktopFilePath"],
      );

  @override
  Future<String> crateApiUnexportBinary(
      {required String containerName, required String binaryPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(containerName, serializer);
        sse_encode_String(binaryPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 34, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiUnexportBinaryConstMeta,
      argValues: [containerName, binaryPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUnexportBinaryConstMeta => const TaskConstMeta(
        debugName: "unexport_binary",
        argNames: ["containerName", "binaryPath"],
      );

  @override
  Future<String> crateApiUpgradeContainer({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 35, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiUpgradeContainerConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUpgradeContainerConstMeta => const TaskConstMeta(
        debugName: "upgrade_container",
        argNames: ["name"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppInfo dco_decode_app_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AppInfo(
      name: dco_decode_String(arr[0]),
      exec: dco_decode_String(arr[1]),
      icon: dco_decode_String(arr[2]),
      desktopFilePath: dco_decode_String(arr[3]),
      isExported: dco_decode_bool(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CreateArgs dco_decode_box_autoadd_create_args(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_create_args(raw);
  }

  @protected
  VolumeMode dco_decode_box_autoadd_volume_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_volume_mode(raw);
  }

  @protected
  ContainerInfo dco_decode_container_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ContainerInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      status: dco_decode_status(arr[2]),
      image: dco_decode_String(arr[3]),
    );
  }

  @protected
  ContainerStats dco_decode_container_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ContainerStats(
      cpuPercent: dco_decode_f_64(arr[0]),
      memoryUsage: dco_decode_String(arr[1]),
      memoryLimit: dco_decode_String(arr[2]),
      memoryPercent: dco_decode_f_64(arr[3]),
      networkIo: dco_decode_String(arr[4]),
      blockIo: dco_decode_String(arr[5]),
    );
  }

  @protected
  CreateArgName dco_decode_create_arg_name(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return CreateArgName(
      field0: dco_decode_String(arr[0]),
    );
  }

  @protected
  CreateArgs dco_decode_create_args(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CreateArgs(
      init: dco_decode_bool(arr[0]),
      nvidia: dco_decode_bool(arr[1]),
      homePath: dco_decode_opt_String(arr[2]),
      image: dco_decode_String(arr[3]),
      name: dco_decode_create_arg_name(arr[4]),
      volumes: dco_decode_list_volume(arr[5]),
    );
  }

  @protected
  ExportedBinary dco_decode_exported_binary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ExportedBinary(
      name: dco_decode_String(arr[0]),
      sourcePath: dco_decode_String(arr[1]),
      exportedPath: dco_decode_String(arr[2]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AppInfo> dco_decode_list_app_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_app_info).toList();
  }

  @protected
  List<ContainerInfo> dco_decode_list_container_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_container_info).toList();
  }

  @protected
  List<ExportedBinary> dco_decode_list_exported_binary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_exported_binary).toList();
  }

  @protected
  List<PackageInfo> dco_decode_list_package_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_package_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SnapshotInfo> dco_decode_list_snapshot_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_snapshot_info).toList();
  }

  @protected
  List<Volume> dco_decode_list_volume(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_volume).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  VolumeMode? dco_decode_opt_box_autoadd_volume_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_volume_mode(raw);
  }

  @protected
  PackageInfo dco_decode_package_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PackageInfo(
      name: dco_decode_String(arr[0]),
      version: dco_decode_String(arr[1]),
      description: dco_decode_String(arr[2]),
      installed: dco_decode_bool(arr[3]),
    );
  }

  @protected
  SnapshotInfo dco_decode_snapshot_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SnapshotInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      created: dco_decode_String(arr[2]),
      size: dco_decode_String(arr[3]),
    );
  }

  @protected
  Status dco_decode_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Status_Up(
          dco_decode_String(raw[1]),
        );
      case 1:
        return Status_Created(
          dco_decode_String(raw[1]),
        );
      case 2:
        return Status_Exited(
          dco_decode_String(raw[1]),
        );
      case 3:
        return Status_Other(
          dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  Volume dco_decode_volume(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Volume(
      hostPath: dco_decode_String(arr[0]),
      containerPath: dco_decode_String(arr[1]),
      mode: dco_decode_opt_box_autoadd_volume_mode(arr[2]),
    );
  }

  @protected
  VolumeMode dco_decode_volume_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VolumeMode.values[raw as int];
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppInfo sse_decode_app_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_exec = sse_decode_String(deserializer);
    var var_icon = sse_decode_String(deserializer);
    var var_desktopFilePath = sse_decode_String(deserializer);
    var var_isExported = sse_decode_bool(deserializer);
    return AppInfo(
        name: var_name,
        exec: var_exec,
        icon: var_icon,
        desktopFilePath: var_desktopFilePath,
        isExported: var_isExported);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CreateArgs sse_decode_box_autoadd_create_args(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_create_args(deserializer));
  }

  @protected
  VolumeMode sse_decode_box_autoadd_volume_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_volume_mode(deserializer));
  }

  @protected
  ContainerInfo sse_decode_container_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_status = sse_decode_status(deserializer);
    var var_image = sse_decode_String(deserializer);
    return ContainerInfo(
        id: var_id, name: var_name, status: var_status, image: var_image);
  }

  @protected
  ContainerStats sse_decode_container_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cpuPercent = sse_decode_f_64(deserializer);
    var var_memoryUsage = sse_decode_String(deserializer);
    var var_memoryLimit = sse_decode_String(deserializer);
    var var_memoryPercent = sse_decode_f_64(deserializer);
    var var_networkIo = sse_decode_String(deserializer);
    var var_blockIo = sse_decode_String(deserializer);
    return ContainerStats(
        cpuPercent: var_cpuPercent,
        memoryUsage: var_memoryUsage,
        memoryLimit: var_memoryLimit,
        memoryPercent: var_memoryPercent,
        networkIo: var_networkIo,
        blockIo: var_blockIo);
  }

  @protected
  CreateArgName sse_decode_create_arg_name(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    return CreateArgName(field0: var_field0);
  }

  @protected
  CreateArgs sse_decode_create_args(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_init = sse_decode_bool(deserializer);
    var var_nvidia = sse_decode_bool(deserializer);
    var var_homePath = sse_decode_opt_String(deserializer);
    var var_image = sse_decode_String(deserializer);
    var var_name = sse_decode_create_arg_name(deserializer);
    var var_volumes = sse_decode_list_volume(deserializer);
    return CreateArgs(
        init: var_init,
        nvidia: var_nvidia,
        homePath: var_homePath,
        image: var_image,
        name: var_name,
        volumes: var_volumes);
  }

  @protected
  ExportedBinary sse_decode_exported_binary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_sourcePath = sse_decode_String(deserializer);
    var var_exportedPath = sse_decode_String(deserializer);
    return ExportedBinary(
        name: var_name,
        sourcePath: var_sourcePath,
        exportedPath: var_exportedPath);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AppInfo> sse_decode_list_app_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AppInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_app_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<ContainerInfo> sse_decode_list_container_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ContainerInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_container_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<ExportedBinary> sse_decode_list_exported_binary(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ExportedBinary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_exported_binary(deserializer));
    }
    return ans_;
  }

  @protected
  List<PackageInfo> sse_decode_list_package_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PackageInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_package_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SnapshotInfo> sse_decode_list_snapshot_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SnapshotInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_snapshot_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<Volume> sse_decode_list_volume(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Volume>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_volume(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  VolumeMode? sse_decode_opt_box_autoadd_volume_mode(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_volume_mode(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PackageInfo sse_decode_package_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_installed = sse_decode_bool(deserializer);
    return PackageInfo(
        name: var_name,
        version: var_version,
        description: var_description,
        installed: var_installed);
  }

  @protected
  SnapshotInfo sse_decode_snapshot_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_created = sse_decode_String(deserializer);
    var var_size = sse_decode_String(deserializer);
    return SnapshotInfo(
        id: var_id, name: var_name, created: var_created, size: var_size);
  }

  @protected
  Status sse_decode_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return Status_Up(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return Status_Created(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return Status_Exited(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return Status_Other(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  Volume sse_decode_volume(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hostPath = sse_decode_String(deserializer);
    var var_containerPath = sse_decode_String(deserializer);
    var var_mode = sse_decode_opt_box_autoadd_volume_mode(deserializer);
    return Volume(
        hostPath: var_hostPath,
        containerPath: var_containerPath,
        mode: var_mode);
  }

  @protected
  VolumeMode sse_decode_volume_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return VolumeMode.values[inner];
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_info(AppInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.exec, serializer);
    sse_encode_String(self.icon, serializer);
    sse_encode_String(self.desktopFilePath, serializer);
    sse_encode_bool(self.isExported, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_create_args(
      CreateArgs self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_create_args(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_volume_mode(
      VolumeMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_volume_mode(self, serializer);
  }

  @protected
  void sse_encode_container_info(ContainerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_status(self.status, serializer);
    sse_encode_String(self.image, serializer);
  }

  @protected
  void sse_encode_container_stats(
      ContainerStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.cpuPercent, serializer);
    sse_encode_String(self.memoryUsage, serializer);
    sse_encode_String(self.memoryLimit, serializer);
    sse_encode_f_64(self.memoryPercent, serializer);
    sse_encode_String(self.networkIo, serializer);
    sse_encode_String(self.blockIo, serializer);
  }

  @protected
  void sse_encode_create_arg_name(
      CreateArgName self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.field0, serializer);
  }

  @protected
  void sse_encode_create_args(CreateArgs self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.init, serializer);
    sse_encode_bool(self.nvidia, serializer);
    sse_encode_opt_String(self.homePath, serializer);
    sse_encode_String(self.image, serializer);
    sse_encode_create_arg_name(self.name, serializer);
    sse_encode_list_volume(self.volumes, serializer);
  }

  @protected
  void sse_encode_exported_binary(
      ExportedBinary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_String(self.exportedPath, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_app_info(List<AppInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_app_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_container_info(
      List<ContainerInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_container_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_exported_binary(
      List<ExportedBinary> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_exported_binary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_package_info(
      List<PackageInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_package_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_snapshot_info(
      List<SnapshotInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_snapshot_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_volume(List<Volume> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_volume(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_volume_mode(
      VolumeMode? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_volume_mode(self, serializer);
    }
  }

  @protected
  void sse_encode_package_info(PackageInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_bool(self.installed, serializer);
  }

  @protected
  void sse_encode_snapshot_info(SnapshotInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.created, serializer);
    sse_encode_String(self.size, serializer);
  }

  @protected
  void sse_encode_status(Status self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Status_Up(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case Status_Created(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case Status_Exited(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case Status_Other(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_volume(Volume self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.hostPath, serializer);
    sse_encode_String(self.containerPath, serializer);
    sse_encode_opt_box_autoadd_volume_mode(self.mode, serializer);
  }

  @protected
  void sse_encode_volume_mode(VolumeMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
