#!/usr/bin/env python3
"""Generate Flatpak cargo-sources.json from the workspace Cargo.lock.

Ported from Gosh-Yubico-Authenticator-for-Linux/flatpak/generate-cargo-sources.py
(D5: tasks T0/T2/T4 are ports, not greenfield builds). Two paths differ from the
sibling because this repository is a *virtual* workspace whose manifest sits at
the repository root (`core/` today, `app/` joining in S5) rather than in `rust/`:

  --lockfile  defaults to <root>/Cargo.lock        (sibling: <root>/rust/Cargo.lock)
  --project   defaults to <root>                   (sibling: <root>/rust)

`--project` is where `cargo vendor` runs, so it must be the directory holding the
workspace manifest -- pointing it at `core/` would vendor only that member's
subgraph and silently omit everything `app/` will pull in.

Handles both crates.io packages (emitted as `archive` sources from static.crates.io)
and git packages (emitted as `git` sources pinned to the commit recorded in the
lockfile, flattened into the vendor directory by a `shell` source).

Git packages need two things the lockfile does not carry: where in the repository
each package lives, and a manifest with workspace inheritance already resolved.
Those live in git-packages.json and git-manifests/, both generated by --refresh-git
(which needs network) and committed.

Neither carries a URL or a commit: the lockfile source string is the key, and every
pin the generator emits is derived from it. That keeps Cargo.lock the single source
of truth for what gets fetched, so a pin cannot drift between two files. A sidecar
that does not describe exactly the lockfile's git sources is a hard error, so
--check catches staleness without needing the network.

Five git *pointers* matter to this project (D24), but they are not the set of git
*sources* the lockfile records, and the sidecar is keyed on the latter. Resolved at
the pinned libcosmic rev, the lockfile carries **eleven** git sources: libcosmic
(rev-pinned by us), the two unpinned git deps libcosmic's unconditional cfg(unix)
block declares (pop-os/dbus-settings-bindings, pop-os/freedesktop-icons), and eight
reached only through the `iced` submodule's own graph (cosmic-protocols,
rust-atomicwrites, pop-os/winit, softbuffer, window_clipboard, smithay-clipboard,
cryoglyph, wash2/accesskit).

The submodules are not lockfile entries at all. `iced` arrives as path dependencies
inside the libcosmic checkout -- so its crates appear as packages *of the libcosmic
source*, with subdirectory paths -- and `cosmic-icons` arrives as a plain directory
of that same package (dependencies/packaging.md section 1.3 records the detail).
--refresh-git populates submodules while harvesting, which is what makes the iced
packages resolvable at all.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from urllib.parse import urlparse

CRATES_IO = "https://static.crates.io/crates"
CARGO_HOME = "cargo"
CARGO_CRATES = f"{CARGO_HOME}/vendor"
GIT_STAGING = f"{CARGO_HOME}/git-src"
VENDORED_SOURCES = "vendored-sources"

# Qualifiers cargo records in a lockfile git source, in the order it prefers them.
GIT_QUALIFIERS = ("rev", "tag", "branch")


def parse_lockfile(path: Path) -> list[dict[str, str]]:
    packages: list[dict[str, str]] = []
    current: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line == "[[package]]":
            if current:
                packages.append(current)
            current = {}
            continue
        if "=" not in line or line.startswith("["):
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        if key not in {"name", "version", "source", "checksum"}:
            continue
        current[key] = value.strip().strip('"')
    if current:
        packages.append(current)
    return packages


def parse_git_source(source: str) -> dict[str, str]:
    """Split a lockfile `git+URL?qualifier=value#commit` into its parts.

    The commit is the only thing we ever fetch by: a tag or branch is a movable
    ref, and a Flatpak build that tracked one would not be reproducible. The
    qualifier is still recorded because cargo matches its `[source]` config keys
    against the full source string, so it has to be reproduced verbatim there.
    """
    if not source.startswith("git+"):
        raise ValueError(f"not a git source: {source}")
    url_part, _, commit = source[len("git+") :].partition("#")
    if not commit:
        raise SystemExit(f"git source without a locked commit: {source}")
    parsed = urlparse(url_part)
    base_url = url_part.split("?", 1)[0]
    qualifier_kind = ""
    qualifier_value = ""
    if parsed.query:
        for candidate in GIT_QUALIFIERS:
            prefix = f"{candidate}="
            for chunk in parsed.query.split("&"):
                if chunk.startswith(prefix):
                    qualifier_kind = candidate
                    qualifier_value = chunk[len(prefix) :]
                    break
            if qualifier_kind:
                break
        if not qualifier_kind:
            raise SystemExit(f"unrecognised git source qualifier: {source}")
    return {
        "url": base_url,
        "commit": commit,
        "qualifier_kind": qualifier_kind,
        "qualifier_value": qualifier_value,
        # The key cargo uses in `[source."..."]`: the source string without the commit.
        "config_key": url_part,
    }


def repo_slug(url: str, commit: str) -> str:
    name = url.rstrip("/").rsplit("/", 1)[-1]
    if name.endswith(".git"):
        name = name[: -len(".git")]
    return f"{name}-{commit[:8]}"


def crate_sources(package: dict[str, str]) -> list[dict]:
    name = package["name"]
    version = package["version"]
    checksum = package["checksum"]
    dest = f"{CARGO_CRATES}/{name}-{version}"
    return [
        {
            "type": "archive",
            "archive-type": "tar-gzip",
            "url": f"{CRATES_IO}/{name}/{name}-{version}.crate",
            "sha256": checksum,
            "dest": dest,
        },
        {
            "type": "inline",
            "contents": json.dumps({"package": checksum, "files": {}}),
            "dest": dest,
            "dest-filename": ".cargo-checksum.json",
        },
    ]


def git_repo_sources(source: str, info: dict, entry: dict) -> list[dict]:
    """Emit the git checkout, the flattening commands, and the checksum stubs."""
    slug = repo_slug(info["url"], info["commit"])
    staging = f"{GIT_STAGING}/{slug}"

    sources: list[dict] = [
        {
            # `commit` only -- never `branch` or `tag`. See parse_git_source.
            "type": "git",
            "url": info["url"],
            "commit": info["commit"],
            "dest": staging,
        }
    ]

    commands: list[str] = []
    checksums: list[dict] = []
    for key in sorted(entry["packages"]):
        package = entry["packages"][key]
        name, version = key.rsplit(" ", 1)
        dest = f"{CARGO_CRATES}/{name}-{version}"
        subdir = package["path"]
        prefix = staging if subdir == "." else f"{staging}/{subdir}"
        commands.append(f"mkdir -p {dest}")
        for item in package["entries"]:
            # -L dereferences symlinks: several winit sub-crates carry a LICENSE
            # symlink pointing above their own directory, which would dangle once
            # the package is lifted out of the repository.
            commands.append(f"cp -aL {prefix}/{item} {dest}/")
        checksums.append(
            {
                # A vendored package is parsed standalone, with no workspace root
                # above it, so `version.workspace = true` and friends cannot be
                # resolved at build time. Ship the normalised manifest `cargo
                # vendor` produces instead of the in-repo one. This overwrites the
                # Cargo.toml copied above -- inline sources are applied in order.
                "type": "inline",
                "contents": package["manifest"],
                "dest": dest,
                "dest-filename": "Cargo.toml",
            }
        )
        checksums.append(
            {
                "type": "inline",
                # Git packages carry no crate checksum; integrity comes from the
                # pinned commit above. This mirrors what `cargo vendor` writes.
                "contents": json.dumps({"package": None, "files": {}}),
                "dest": dest,
                "dest-filename": ".cargo-checksum.json",
            }
        )
    commands.append(f"rm -rf {staging}")

    sources.append({"type": "shell", "commands": commands})
    sources.extend(checksums)
    return sources


def cargo_config(git_entries: dict[str, dict]) -> str:
    lines = [
        "[source.crates-io]",
        f'replace-with = "{VENDORED_SOURCES}"',
        "",
    ]
    for source in sorted(git_entries):
        info = git_entries[source]["source"]
        lines.append(f'[source."{info["config_key"]}"]')
        lines.append(f'git = "{info["url"]}"')
        if info["qualifier_kind"]:
            lines.append(f'{info["qualifier_kind"]} = "{info["qualifier_value"]}"')
        lines.append(f'replace-with = "{VENDORED_SOURCES}"')
        lines.append("")
    lines.append(f"[source.{VENDORED_SOURCES}]")
    lines.append(f'directory = "{CARGO_CRATES}"')
    lines.append("")
    return "\n".join(lines)


def load_sidecar(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def collect_git_sources(packages: list[dict[str, str]]) -> dict[str, list[dict]]:
    grouped: dict[str, list[dict]] = {}
    for package in packages:
        source = package.get("source", "")
        if source.startswith("git+"):
            grouped.setdefault(source, []).append(package)
    return grouped


def validate_sidecar_entry(source: str, entry: object) -> None:
    """Reject a malformed sidecar with a readable message rather than a KeyError."""
    stale = "rerun: python3 flatpak/generate-cargo-sources.py --refresh-git"
    if not isinstance(entry, dict) or not isinstance(entry.get("packages"), dict):
        raise SystemExit(f"malformed git-packages.json entry for {source}\n{stale}")
    for key, package in entry["packages"].items():
        if (
            not isinstance(package, dict)
            or not isinstance(package.get("path"), str)
            or not isinstance(package.get("entries"), list)
            or not all(isinstance(item, str) for item in package["entries"])
        ):
            raise SystemExit(
                f"malformed git-packages.json entry for {source} package {key}\n{stale}"
            )


def generate(packages: list[dict[str, str]], sidecar: dict, manifests: Path) -> list[dict]:
    sources: list[dict] = []
    git_groups = collect_git_sources(packages)

    for package in packages:
        source = package.get("source", "")
        if not source or source.startswith("git+"):
            continue
        if "checksum" not in package:
            raise SystemExit(f"missing checksum for {package.get('name')}")
        sources.extend(crate_sources(package))

    git_entries: dict[str, dict] = {}
    for source in sorted(git_groups):
        # Parse first: a malformed or commitless source is a lockfile problem, and
        # its own error is far more useful than "rerun --refresh-git", which would
        # not fix it.
        info = parse_git_source(source)
        entry = sidecar.get(source)
        if entry is None:
            raise SystemExit(
                f"no git-packages.json entry for {source}\n"
                "rerun: python3 flatpak/generate-cargo-sources.py --refresh-git"
            )
        validate_sidecar_entry(source, entry)
        expected = {f"{p['name']} {p['version']}" for p in git_groups[source]}
        recorded = set(entry.get("packages", {}))
        if expected != recorded:
            missing = ", ".join(sorted(expected - recorded)) or "-"
            extra = ", ".join(sorted(recorded - expected)) or "-"
            raise SystemExit(
                f"git-packages.json is stale for {source}\n"
                f"  in lockfile but not recorded: {missing}\n"
                f"  recorded but not in lockfile: {extra}\n"
                "rerun: python3 flatpak/generate-cargo-sources.py --refresh-git"
            )
        entry = dict(entry, packages=dict(entry["packages"]))
        for key, package in entry["packages"].items():
            name, version = key.rsplit(" ", 1)
            manifest = manifests / f"{name}-{version}" / "Cargo.toml"
            if not manifest.exists():
                raise SystemExit(
                    f"missing normalised manifest {manifest}\n"
                    "rerun: python3 flatpak/generate-cargo-sources.py --refresh-git"
                )
            entry["packages"][key] = dict(package, manifest=manifest.read_text(encoding="utf-8"))
        git_entries[source] = {"source": info, "entry": entry}
        sources.extend(git_repo_sources(source, info, entry))

    sources.append(
        {
            "type": "inline",
            "contents": cargo_config(git_entries),
            "dest": CARGO_HOME,
            "dest-filename": "config",
        }
    )
    return sources


WORKSPACE_INHERITED = object()


def read_manifest(path: Path) -> dict:
    """Pull the few fields we need out of a Cargo.toml without a TOML parser.

    Returns package name, package version (or WORKSPACE_INHERITED), and the
    [workspace.package] version if this manifest is a workspace root.
    """
    name = None
    version = None
    workspace_version = None
    section = ""
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.split("#", 1)[0].strip()
        if line.startswith("["):
            section = line.strip("[]")
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if section == "package":
            if key == "name" and name is None:
                name = value.strip('"')
            elif key in ("version", "version.workspace") and version is None:
                if key == "version.workspace" or "workspace" in value:
                    version = WORKSPACE_INHERITED
                elif value.startswith('"'):
                    version = value.strip('"')
        elif section == "workspace.package" and key == "version":
            workspace_version = value.strip('"')
    return {"name": name, "version": version, "workspace_version": workspace_version}


def resolve_version(manifest: Path, parsed: dict, root: Path) -> str | None:
    """Resolve `version.workspace = true` against the nearest ancestor workspace."""
    if parsed["version"] is not WORKSPACE_INHERITED:
        return parsed["version"]
    # A manifest can be both a package and its own workspace root -- iced/Cargo.toml
    # is exactly that -- so check it before walking up.
    if parsed["workspace_version"]:
        return parsed["workspace_version"]
    directory = manifest.parent.parent
    while True:
        candidate = directory / "Cargo.toml"
        if candidate.exists():
            inherited = read_manifest(candidate)["workspace_version"]
            if inherited:
                return inherited
        if directory == root or root not in directory.parents:
            return None
        directory = directory.parent


def package_manifests(root: Path) -> dict[str, Path]:
    """Map "name version" -> directory, for every Cargo.toml under root."""
    found: dict[str, list[Path]] = {}
    for manifest in root.rglob("Cargo.toml"):
        if ".git" in manifest.parts or "target" in manifest.parts:
            continue
        parsed = read_manifest(manifest)
        name = parsed["name"]
        version = resolve_version(manifest, parsed, root)
        if name and version:
            found.setdefault(f"{name} {version}", []).append(manifest.parent)
    resolved: dict[str, Path] = {}
    for key, dirs in found.items():
        if len(dirs) > 1:
            raise SystemExit(
                f"ambiguous package {key} in {root}: " + ", ".join(str(d) for d in dirs)
            )
        resolved[key] = dirs[0]
    return resolved


def harvest_manifests(project: Path, manifests: Path, wanted: set[str]) -> int:
    """Capture the normalised Cargo.toml `cargo vendor` writes for each git package.

    A vendored package is parsed on its own, with no workspace above it, so the
    in-repo manifest of a workspace member is unusable -- cargo fails with
    "error inheriting `edition` from workspace root manifest". `cargo vendor`
    resolves that inheritance, so we take its output as the source of truth rather
    than reimplementing cargo's manifest normalisation.
    """
    if manifests.exists():
        shutil.rmtree(manifests)
    manifests.mkdir(parents=True)
    with tempfile.TemporaryDirectory(prefix="cargo-vendor-harvest-") as tmp:
        target = Path(tmp) / "vendor"
        print(f"running cargo vendor in {project} (downloads the full graph)", file=sys.stderr)
        subprocess.run(
            ["cargo", "vendor", "--locked", "--versioned-dirs", str(target)],
            cwd=project,
            check=True,
            stdout=subprocess.DEVNULL,
        )
        written = 0
        for key in sorted(wanted):
            name, version = key.rsplit(" ", 1)
            source = target / f"{name}-{version}" / "Cargo.toml"
            if not source.exists():
                raise SystemExit(f"cargo vendor produced no manifest for {key}")
            destination = manifests / f"{name}-{version}"
            destination.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, destination / "Cargo.toml")
            written += 1
    return written


def refresh_git(lockfile: Path, output: Path, manifests: Path, project: Path) -> int:
    packages = parse_lockfile(lockfile)
    git_groups = collect_git_sources(packages)
    if not git_groups:
        output.write_text("{}\n", encoding="utf-8")
        if manifests.exists():
            shutil.rmtree(manifests)
        print(f"wrote {output} (no git dependencies)")
        return 0

    wanted_all = {
        f"{p['name']} {p['version']}"
        for group in git_groups.values()
        for p in group
    }
    normalised = harvest_manifests(project, manifests, wanted_all)
    print(f"harvested {normalised} normalised manifests into {manifests}", file=sys.stderr)

    sidecar: dict[str, dict] = {}
    with tempfile.TemporaryDirectory(prefix="cargo-git-refresh-") as tmp:
        for source in sorted(git_groups):
            info = parse_git_source(source)
            checkout = Path(tmp) / repo_slug(info["url"], info["commit"])
            print(f"cloning {info['url']} @ {info['commit'][:8]}", file=sys.stderr)
            subprocess.run(["git", "init", "--quiet", str(checkout)], check=True)
            subprocess.run(
                ["git", "-C", str(checkout), "remote", "add", "origin", info["url"]],
                check=True,
            )
            subprocess.run(
                ["git", "-C", str(checkout), "fetch", "--quiet", "--depth", "1",
                 "origin", info["commit"]],
                check=True,
            )
            subprocess.run(
                ["git", "-C", str(checkout), "checkout", "--quiet", "FETCH_HEAD"],
                check=True,
            )
            # libcosmic depends on the iced_* family by path into a submodule, so
            # the submodules are not optional -- 18 of its packages live in them.
            subprocess.run(
                ["git", "-C", str(checkout), "submodule", "update", "--init",
                 "--recursive", "--depth", "1", "--quiet"],
                check=True,
            )

            manifests = package_manifests(checkout)
            wanted = {f"{p['name']} {p['version']}" for p in git_groups[source]}
            missing = sorted(wanted - set(manifests))
            if missing:
                raise SystemExit(
                    f"{info['url']} @ {info['commit'][:8]} does not contain: "
                    + ", ".join(missing)
                )

            subpaths = {
                key: manifests[key].relative_to(checkout).as_posix() or "."
                for key in sorted(wanted)
            }
            subpaths = {k: (v if v else ".") for k, v in subpaths.items()}

            entries: dict[str, dict] = {}
            for key, subpath in subpaths.items():
                package_dir = checkout if subpath == "." else checkout / subpath
                # Exclude anything that is the root of another vendored package;
                # cargo vendor does the same, and it is what keeps the libcosmic
                # directory from swallowing the whole iced submodule.
                others = [
                    other
                    for other_key, other in subpaths.items()
                    if other_key != key and other != "." and
                    (subpath == "." or other.startswith(f"{subpath}/"))
                ]
                shadowed = set()
                for other in others:
                    rest = other if subpath == "." else other[len(subpath) + 1 :]
                    shadowed.add(rest.split("/", 1)[0])
                # Skip dot-entries (.git, .github, .vscode, .gitmodules ...) to match
                # what `cargo vendor` produces -- that equivalence is the validation
                # oracle for this whole mechanism, so it is worth preserving exactly.
                keep = sorted(
                    item.name
                    for item in package_dir.iterdir()
                    if not item.name.startswith(".") and item.name not in shadowed
                )
                entries[key] = {"path": subpath, "entries": keep}

            # Deliberately no url/commit here. The lockfile source string is the
            # dict key and is the single source of truth for both; duplicating
            # them would create a second place a pin could drift (R8). Everything
            # emitted is derived from the key via parse_git_source.
            sidecar[source] = {"packages": entries}

    output.write_text(json.dumps(sidecar, indent=4, sort_keys=True) + "\n", encoding="utf-8")
    total = sum(len(v["packages"]) for v in sidecar.values())
    print(f"wrote {output} ({len(sidecar)} git remotes, {total} packages)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    root = Path(__file__).resolve().parents[1]
    parser.add_argument("--lockfile", type=Path, default=root / "Cargo.lock")
    parser.add_argument(
        "--output", type=Path, default=Path(__file__).resolve().parent / "cargo-sources.json"
    )
    parser.add_argument(
        "--git-packages",
        type=Path,
        default=Path(__file__).resolve().parent / "git-packages.json",
        help="sidecar mapping git packages to their subdirectory in the repository",
    )
    parser.add_argument(
        "--git-manifests",
        type=Path,
        default=Path(__file__).resolve().parent / "git-manifests",
        help="directory of normalised Cargo.toml files for git packages",
    )
    parser.add_argument(
        "--project",
        type=Path,
        default=root,
        help="cargo workspace to vendor from when refreshing normalised manifests",
    )
    parser.add_argument(
        "--refresh-git",
        action="store_true",
        help="clone each git dependency at its locked commit and rebuild the sidecar "
        "(requires network; run whenever the git set in Cargo.lock changes)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if cargo-sources.json does not match the lockfile",
    )
    args = parser.parse_args()

    if args.refresh_git:
        return refresh_git(args.lockfile, args.git_packages, args.git_manifests, args.project)

    packages = parse_lockfile(args.lockfile)
    sidecar = load_sidecar(args.git_packages)
    generated = generate(packages, sidecar, args.git_manifests)
    serialized = json.dumps(generated, indent=4) + "\n"

    if args.check:
        if not args.output.exists():
            print(f"missing {args.output}", file=sys.stderr)
            return 1
        current = args.output.read_text(encoding="utf-8")
        if current != serialized:
            print(f"{args.output} is out of date; rerun generate-cargo-sources.py", file=sys.stderr)
            return 1
        print(f"{args.output} matches {args.lockfile}")
        return 0

    args.output.write_text(serialized, encoding="utf-8")
    crate_count = sum(1 for p in packages if p.get("checksum"))
    git_count = sum(1 for p in packages if p.get("source", "").startswith("git+"))
    print(f"wrote {args.output} ({crate_count} crates, {git_count} git packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
