// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'distrobox.freezed.dart';

class ContainerInfo {
  final String id;
  final String name;
  final Status status;
  final String image;

  const ContainerInfo({
    required this.id,
    required this.name,
    required this.status,
    required this.image,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ status.hashCode ^ image.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContainerInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          status == other.status &&
          image == other.image;
}

/// Resource usage statistics for a container
class ContainerStats {
  final double cpuPercent;
  final String memoryUsage;
  final String memoryLimit;
  final double memoryPercent;
  final String networkIo;
  final String blockIo;

  const ContainerStats({
    required this.cpuPercent,
    required this.memoryUsage,
    required this.memoryLimit,
    required this.memoryPercent,
    required this.networkIo,
    required this.blockIo,
  });

  @override
  int get hashCode =>
      cpuPercent.hashCode ^
      memoryUsage.hashCode ^
      memoryLimit.hashCode ^
      memoryPercent.hashCode ^
      networkIo.hashCode ^
      blockIo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContainerStats &&
          runtimeType == other.runtimeType &&
          cpuPercent == other.cpuPercent &&
          memoryUsage == other.memoryUsage &&
          memoryLimit == other.memoryLimit &&
          memoryPercent == other.memoryPercent &&
          networkIo == other.networkIo &&
          blockIo == other.blockIo;
}

class CreateArgName {
  final String field0;

  const CreateArgName({
    required this.field0,
  });

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateArgName &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class CreateArgs {
  final bool init;
  final bool nvidia;
  final String? homePath;
  final String image;
  final CreateArgName name;
  final List<Volume> volumes;

  const CreateArgs({
    required this.init,
    required this.nvidia,
    this.homePath,
    required this.image,
    required this.name,
    required this.volumes,
  });

  @override
  int get hashCode =>
      init.hashCode ^
      nvidia.hashCode ^
      homePath.hashCode ^
      image.hashCode ^
      name.hashCode ^
      volumes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateArgs &&
          runtimeType == other.runtimeType &&
          init == other.init &&
          nvidia == other.nvidia &&
          homePath == other.homePath &&
          image == other.image &&
          name == other.name &&
          volumes == other.volumes;
}

/// Information about an installed or available package
class PackageInfo {
  final String name;
  final String version;
  final String description;
  final bool installed;

  const PackageInfo({
    required this.name,
    required this.version,
    required this.description,
    required this.installed,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      version.hashCode ^
      description.hashCode ^
      installed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PackageInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          version == other.version &&
          description == other.description &&
          installed == other.installed;
}

/// Information about a container snapshot
class SnapshotInfo {
  final String id;
  final String name;
  final String created;
  final String size;

  const SnapshotInfo({
    required this.id,
    required this.name,
    required this.created,
    required this.size,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ created.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SnapshotInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          created == other.created &&
          size == other.size;
}

@freezed
sealed class Status with _$Status {
  const Status._();

  const factory Status.up(
    String field0,
  ) = Status_Up;
  const factory Status.created(
    String field0,
  ) = Status_Created;
  const factory Status.exited(
    String field0,
  ) = Status_Exited;
  const factory Status.other(
    String field0,
  ) = Status_Other;
}

class Volume {
  final String hostPath;
  final String containerPath;
  final VolumeMode? mode;

  const Volume({
    required this.hostPath,
    required this.containerPath,
    this.mode,
  });

  @override
  int get hashCode =>
      hostPath.hashCode ^ containerPath.hashCode ^ mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Volume &&
          runtimeType == other.runtimeType &&
          hostPath == other.hostPath &&
          containerPath == other.containerPath &&
          mode == other.mode;
}

enum VolumeMode {
  readOnly,
  ;
}
